### ISSUE TITLE
Split up Pepicons sets

### ISSUE THREAD

**Issue by mesqueeb** [iconify/icon-sets#72] opened 2022-12-14 08:01 UTC
Hey, I'm the author of Pepicons:
https://github.com/iconify/icon-sets/blob/master/json/pepicons.json

Is there anyway I can provide you with my icon set but split up into 2 separate sets: `Pepicons Print` and `Pepicons Pop`.

As you can see on the website: https://pepicons.com

they're very different and are not meant to be mixed.

Any guidance is much appreciated!

**Comment by cyberalien** [comment] 2022-12-14 08:06
Sure, that can be done.

Currently it is available as `pepicons` with mix of icons. It can be split to `pepicons-print` for Print version, `pepicons-pop` for Pop version or something like that. Would that be ok or do you prefer them split differently?

**Comment by mesqueeb** [comment] 2022-12-14 13:33
@cyberalien that would be very kind! That's exactly what I was thinking.  : ) 

Btw is there anything I can set up in my repo to make the process smoother for you ?

**Comment by cyberalien** [comment] 2022-12-15 13:20
Done. Added it to update script, so it will appear as split icon set after tomorrow's update.

Just to avoid confusion. You've mentioned that pop and print icon sets are different and are not meant to be mixed. On your website print icon set has black outline, but in Iconify icon sets it uses icon color for outline. After split it will remain like it was, with `currentColor` for outline, not black color. That is not a bug. Mixing hardcoded palette and text color is not acceptable for icons for multiple reasons, so black color is changed to `currentColor` by parser.

**Comment by cyberalien** [comment] 2022-12-16 10:26
Icon set was split earlier today.

Just noticed a bug: when browsing icon sets, icon grid is not shown for split icon sets, it will be fixed in next update. It doesn't affect functionality, only shown in icon sets list.

Old `pepicons` prefix will continue to be usable, so users who do use icons won't have to change code.

**Closed by cyberalien** 2022-12-16 10:26 UTC

**Comment by mesqueeb** [comment] 2023-05-23 08:31
@cyberalien I've recently updated Pepicons to a new major version and have a new icon type "pencil".

I've also improved the exported .zip on my website: https://pepicons.com

Can I help update the pepicons for this library?

**Comment by cyberalien** [comment] 2023-05-23 17:07
Yes, I do need your help to update package.

Parser cannot update it because directory structure has changed. Directory `svg` no longer exists, new file and directory names are very confusing, so not sure what's going on there.

Directory names seems to include category + icon type now? What confuses me the most is excessively long icon names, can you tell me how to get icon name from that?

**Comment by mesqueeb** [comment] 2023-05-23 22:33
@cyberalien  Thank you for your message.
I moved the svg folder to the `.gitignore` since it's auto-generated and exposed in the npm hosted version.
There's a couple things we can do to bring it back for you:
1. you could use the npm hosted repository instead, which _does_ include the svg folder
2. you could _build_ the repo in order to generate the svg folder: `npm i && npm run _prepare-pepicons && npm run build -w=pepicons`
3. I could remove the svg folder from `.gitignore` and make sure it's commited to github again

I don't have any issues with option 3, let me know if that is what is easiest for you.

---

### concerning the duo-color for print icons:
The "print" icons used to have a mix between `currentColor` and `black` that I now changed to be `currentColor` and `dimgray` (better support when importing into figma)

However, thinking back at your comment that any icon with duo-tone colors is not an icon, I'm thinking that perhaps I could do another update that makes it so print icons work with _just_ `currentColor` for both the shadow and the stroke, and the shadow part is inside of a group that has `opacity="0.2"` (opposed to now, where there is a separate color for the stroke and the shadow, and the shadow is inside of a group that has `opacity="0.8"`)

It would look something like this:

<img width="165" alt="image" src="https://github.com/iconify/icon-sets/assets/3253920/2c6fef44-7f4e-4fbf-93de-93aeafa4181d">

What do you think?

**Comment by mesqueeb** [comment] 2023-05-24 06:03
I am rewriting a lot of pepicons now to include these fixes:
- all icon svg-files in `svg` folder to be bundled in git repository once more for your build pipeline
- print icons to only rely on `currentColor` instead of both `currentColor` _and_ `black`
- toning down the print icons shadow to `opacity="0.2"` instead of `0.8` right now

I will update here when all these fixes are made

**Comment by cyberalien** [comment] 2023-05-24 17:16
Thanks!

There is one more small issue: many icons are 26x26 instead of 20x20. Is that a bug or intentional?

**Comment by cyberalien** [comment] 2023-05-24 17:23
Icon sets updated, `pepicons-pencil` added.

**Comment by mesqueeb** [comment] 2023-05-24 21:22
@cyberalien that's a bug 🤔 they should all be 20x20. I'll look into this. 

Going forward will pepicons be able to get auto-updated? I'll make sure to not move the svgs folder.

**Comment by cyberalien** [comment] 2023-05-24 21:25
Yes, all icon sets are updated automatically.

Example of 26x26 icon: https://github.com/CyCraft/pepicons/blob/dev/packages/pepicons/svg/pop/alarm-circle-filled.svg

**Comment by mesqueeb** [comment] 2023-05-24 21:31
Aha, yes, those -circle type icons are all using a different 26x26 viewbox. That's intentional. But they do keep their width/height at twenty. So without any size adjustments they should appear a bit smaller on the screen (because they have an addintional circle around them)

Btw, I have a list of synonyms per icon to make icons more discoverable (in a JSON). Is there any way you will create a feature where I can provide that to you? Eg. Searching `house` will make my house icon show up but not searching `home`. So I put `home` as a synonym for `house`.
